### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by erhhung** [3scale/3scale_ws_api_for_nodejs#8]
I see that all of the client auth methods are not listening on the https.request 'error' event, and so when a lower level network error occurs, my app has no way of handling the auth failure, and the process just exits. For example, if I'm testing my app behind a firewall proxy, the call will eventually time out:

Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete](net.js:892:19)

I also see simple error strings being 'throw'n on failures, and my callback has no way to handle those, either, due to the async functions. I know I can use a global unhandledException handler, but that's not recommended.

**Comment by mpguerra** [comment]
@picsoung same with this one, not sure if related to #36
